[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "upmaplus" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "langchain-core>=1.6.0",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.optional-dependencies]
wiki = [
    "mcp[cli]>=2.1.1",
    "redis>=8.1.0",
]
long-term-memory = [
    "graphiti-core[falkordb,google-genai]>=0.29.3",
]

[project.scripts]
agent = "agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
